name: dart_simple_backend_shelf
description: Semana do Backend - Flutterando Jul-2022 - Shelf Webserver - Dart
version: 1.0.0

environment:
  sdk: '>=2.18.0-271.0.dev <3.0.0'

dependencies:
  shelf: ^1.3.1
  shelf_modular: ^2.0.0-dev.3
  postgres: ^2.4.5
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.4.1
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
